/* CONFIG - Synced with Figma Make's autogenerated info.tsx */

// ✅ CORRECT projectId from /utils/supabase/info.tsx (autogenerated by Figma Make)
export const projectId = "shspfbpqdctargcjhnke";

// ✅ CORRECT publicAnonKey from /utils/supabase/info.tsx (autogenerated by Figma Make)
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoc3BmYnBxZGN0YXJnY2pobmtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NjgzMTMsImV4cCI6MjA3ODE0NDMxM30.4sZudo6wR6SAFeUzTm_Q3hGogbmFPzy6oKqD4vGAUCU";

// This file exists to centralize Supabase config across the app
// Always keep values in sync with Figma Make's autogenerated /utils/supabase/info.tsx